const initialMovements = [
  {id:1,description:'Nómina quincenal',category:'Trabajo',date:'2026-09-01',account:'Cuenta de Eli',amount:5850,type:'income',icon:'↗',iconClass:'work'},
  {id:2,description:'Supermercado Fresh Market',category:'Comida',date:'2026-09-03',account:'Cuenta compartida',amount:186.42,type:'expense',icon:'⌂',iconClass:'food'},
  {id:3,description:'Pago de electricidad',category:'Vivienda',date:'2026-09-03',account:'Cuenta de Wil',amount:128.75,type:'expense',icon:'⌂',iconClass:'home'},
  {id:4,description:'Gasolina',category:'Transporte',date:'2026-09-02',account:'Cuenta de Eli',amount:64.30,type:'expense',icon:'↗',iconClass:'transport'},
  {id:5,description:'Transferencia recibida',category:'Trabajo',date:'2026-09-02',account:'Cuenta de Wil',amount:4100,type:'income',icon:'↗',iconClass:'work'},
  {id:6,description:'Cena familiar',category:'Comida',date:'2026-08-30',account:'Cuenta compartida',amount:92.18,type:'expense',icon:'⌂',iconClass:'food'},
  {id:7,description:'Consulta médica',category:'Salud',date:'2026-08-28',account:'Cuenta de Eli',amount:65,type:'expense',icon:'+',iconClass:'home'}
];
const demoPayments = [
  {id:1,day:'06',month:'SEP',name:'Renta / hipoteca',detail:'Cuenta compartida · vence en 2 días',amount:1200,status:'pending',account:'Cuenta compartida'},
  {id:2,day:'12',month:'SEP',name:'Internet y teléfono',detail:'Cuenta de Wil · vence en 8 días',amount:85,status:'pending',account:'Cuenta de Wil'},
  {id:3,day:'18',month:'SEP',name:'Seguro del auto',detail:'Cuenta de Eli · vence en 14 días',amount:150,status:'pending',account:'Cuenta de Eli'},
  {id:4,day:'01',month:'SEP',name:'Suscripción de música',detail:'Cuenta de Eli · pagado',amount:14.99,status:'paid',account:'Cuenta de Eli'},
  {id:5,day:'03',month:'SEP',name:'Guardería',detail:'Cuenta compartida · pagado',amount:420,status:'paid',account:'Cuenta compartida'}
];
const $ = (id) => document.getElementById(id);
const money = (n) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n) || 0);
const dateLabel = (date) => new Intl.DateTimeFormat('es-US',{day:'2-digit',month:'short'}).format(new Date(`${date}T12:00:00`)).replace('.','');
const backend = window.CasaClaraBackend;
let state = {profile:'eli',view:'overview',mode:'demo',session:null,currentName:'Eli',members:[],accounts:[],movements:JSON.parse(localStorage.getItem('casa-clara-movements') || 'null') || initialMovements,payments:demoPayments};
function currentAccount(accountId){return state.accounts.find((account)=>account.id===accountId);}
function accountLabel(accountId){return currentAccount(accountId)?.name || 'Cuenta compartida';}
function accountForMovement(movement){return movement.accountId ? currentAccount(movement.accountId) : null;}
function visibleMovements(){
  if(state.mode==='demo'){if(state.profile==='eli')return state.movements.filter((m)=>m.account.includes('Eli')||m.account.includes('compartida'));if(state.profile==='wil')return state.movements.filter((m)=>m.account.includes('Wil')||m.account.includes('compartida'));return state.movements;}
  if(state.profile==='family')return state.movements;
  return state.movements.filter((movement)=>{const account=accountForMovement(movement);return account?.kind==='shared'||account?.owner_id===state.session?.user?.id;});
}
function visiblePayments(){
  if(state.mode==='demo'){if(state.profile==='eli')return state.payments.filter((p)=>p.account.includes('Eli')||p.account.includes('compartida'));if(state.profile==='wil')return state.payments.filter((p)=>p.account.includes('Wil')||p.account.includes('compartida'));return state.payments;}
  if(state.profile==='family')return state.payments;
  return state.payments.filter((payment)=>{const account=currentAccount(payment.accountId);return account?.kind==='shared'||account?.owner_id===state.session?.user?.id;});
}
function showAuth(message=''){$('authOverlay')?.classList.remove('hidden');if($('authMessage'))$('authMessage').textContent=message;}
function hideAuth(){$('authOverlay')?.classList.add('hidden');}
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2600);}
function renderProfile(){
  const family=state.profile==='family';const name=family?'Familia':state.mode==='remote'?state.currentName:(state.profile==='eli'?'Eli':'Wil');const initial=family?'+':name[0]||'E';
  ['profileName','topProfileLabel'].forEach((id)=>$(id).textContent=name);$('profileEmail').textContent=family?'Eli + Wil':state.mode==='remote'?(state.session?.user?.email||'Cuenta personal'):'Cuenta personal';
  ['profileAvatar','topAvatar'].forEach((id)=>{$(id).textContent=initial;$(id).className=`avatar ${state.profile==='eli'?'avatar-eli':state.profile==='wil'?'avatar-wil':'avatar-family'}`;});$('pageTitle').innerHTML=family?'Resumen de Eli y Wil <span class="wave">✺</span>':`Buenos días, ${name} <span class="wave">✺</span>`;
}
function renderAccountOptions(){const select=$('movementForm')?.elements?.account;if(!select||state.mode==='demo')return;select.innerHTML=state.accounts.map((account)=>`<option value="${account.id}">${account.name}</option>`).join('')||'<option value="">Sin cuentas disponibles</option>';}
function renderPayments(){
  const list=visiblePayments();const html=list.slice(0,3).map((p)=>`<div class="payment-item"><div class="payment-date"><strong>${String(p.day).padStart(2,'0')}</strong>${p.month||'SEP'}</div><div class="payment-info"><strong>${p.name}</strong><small>${p.detail||accountLabel(p.accountId)}</small></div><span class="payment-amount">${money(p.amount)}</span></div>`).join('');
  $('paymentPreview').innerHTML=html||'<div class="empty-state">No hay pagos registrados todavía.</div>';$('fullPaymentList').innerHTML=list.map((p)=>`<div class="full-payment-card"><div class="payment-date"><strong>${String(p.day).padStart(2,'0')}</strong>${p.month||'SEP'}</div><div class="payment-info"><strong>${p.name}</strong><small>${p.detail||accountLabel(p.accountId)}</small></div><span class="status ${p.status}">${p.status==='paid'?'Pagado':'Pendiente'}</span><strong class="payment-amount">${money(p.amount)}</strong></div>`).join('')||'<div class="empty-state">No hay pagos registrados todavía.</div>';
  const pending=list.filter((p)=>p.status==='pending');$('dueTotal').textContent=money(pending.reduce((a,p)=>a+Number(p.amount),0));$('pendingCount').textContent=pending.length;$('navPaymentBadge').textContent=pending.length;
}
function renderFamilyReport(){
  if(state.mode!=='remote')return;const all=state.movements;const income=all.filter((m)=>m.type==='income').reduce((sum,m)=>sum+Number(m.amount),0);const expense=all.filter((m)=>m.type==='expense').reduce((sum,m)=>sum+Number(m.amount),0);const opening=state.accounts.reduce((sum,a)=>sum+Number(a.opening_balance||0),0);
  $('familyIncomeValue').textContent=money(income);$('familyExpenseValue').textContent=money(expense);$('familySavingsValue').textContent=money(income-expense);$('familyBalanceValue').textContent=money(opening+income-expense);
  const people=state.members.map((member)=>({member,income:all.filter((m)=>accountForMovement(m.accountId)?.owner_id===member.user_id&&m.type==='income').reduce((sum,m)=>sum+Number(m.amount),0)}));const totalPersonal=people.reduce((sum,p)=>sum+p.income,0);const eli=people.find((p)=>/eli/i.test(p.member.display_name));const wil=people.find((p)=>/wil/i.test(p.member.display_name));
  if(eli){$('eliIncomeValue').textContent=money(eli.income);$('eliIncomePct').textContent=`${totalPersonal?Math.round(eli.income/totalPersonal*100):0}%`;}if(wil){$('wilIncomeValue').textContent=money(wil.income);$('wilIncomePct').textContent=`${totalPersonal?Math.round(wil.income/totalPersonal*100):0}%`;}
}
function renderMovements(){
  const list=visibleMovements().slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('movementPreview').innerHTML=list.slice(0,4).map((m)=>`<div class="movement-item"><span class="movement-icon ${m.iconClass}">${m.icon}</span><div class="movement-info"><strong>${m.description}</strong><small>${m.category} · ${m.account}</small></div><span class="movement-amount ${m.type}">${m.type==='income'?'+':'−'}${money(m.amount)}</span></div>`).join('')||'<div class="empty-state">No hay movimientos registrados todavía.</div>';
  const query=($('movementSearch')?.value||'').toLowerCase();const type=$('movementTypeFilter')?.value||'all';const category=$('movementCategoryFilter')?.value||'all';const filtered=list.filter((m)=>(!query||`${m.description} ${m.category}`.toLowerCase().includes(query))&&(type==='all'||m.type===type)&&(category==='all'||m.category===category));
  $('movementTable').innerHTML=filtered.map((m)=>`<div class="table-row"><div class="movement-cell"><span class="movement-icon ${m.iconClass}">${m.icon}</span><strong>${m.description}</strong></div><div><span class="category-chip">${m.category}</span></div><div>${dateLabel(m.date)}</div><div>${m.account}</div><div class="align-right movement-amount ${m.type}">${m.type==='income'?'+':'−'}${money(m.amount)}</div></div>`).join('')||'<div class="empty-state">No hay movimientos con estos filtros.</div>';
  const month=new Date().toISOString().slice(0,7);const current=list.filter((m)=>String(m.date).startsWith(month));const income=current.filter((m)=>m.type==='income').reduce((a,m)=>a+Number(m.amount),0);const expense=current.filter((m)=>m.type==='expense').reduce((a,m)=>a+Number(m.amount),0);$('incomeValue').textContent=money(income);$('expenseValue').textContent=money(expense);
  const base=state.mode==='remote'?state.accounts.filter((account)=>state.profile==='family'||account.kind==='shared'||account.owner_id===state.session?.user?.id).reduce((sum,a)=>sum+Number(a.opening_balance||0),0):6500;$('balanceValue').textContent=money(base+income-expense);const cats={};current.filter((m)=>m.type==='expense').forEach((m)=>cats[m.category]=(cats[m.category]||0)+Number(m.amount));const colors=['#74b98c','#e4bc97','#b9a5d6','#8bbbc5','#e9dcae'];$('categoryList').innerHTML=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,val],i)=>`<div class="category-item"><i style="background:${colors[i]}"/><span>${name}<small>${Math.round(val/Math.max(expense,1)*100)}% del total</small></span><strong>${money(val)}</strong></div>`).join('')||'<div class="empty-state">Sin gastos en este periodo.</div>';renderFamilyReport();
}
function switchView(view){state.view=view;document.querySelectorAll('.view-panel').forEach((p)=>p.classList.add('hidden'));$(`${view}View`).classList.remove('hidden');document.querySelectorAll('.nav-item[data-view]').forEach((b)=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});}
function openModal(id){$(id).classList.remove('hidden');if(id==='movementModal')$('movementForm').date.value=new Date().toISOString().slice(0,10);}
function closeModal(id){$(id).classList.add('hidden');}
function enterDemo(){state.mode='demo';state.session=null;state.profile='eli';state.currentName='Eli';hideAuth();renderProfile();renderPayments();renderMovements();switchView('overview');}
function addSignOutButton(){if(state.mode!=='remote'||$('signOutButton'))return;const button=document.createElement('button');button.id='signOutButton';button.className='signout-button';button.type='button';button.textContent='Salir';button.addEventListener('click',async()=>{await backend.signOut();state.session=null;state.mode='demo';showAuth('Sesión cerrada.');});$('topProfileButton').parentElement.appendChild(button);}
async function loadRemoteData(session){
  state.session=session;state.mode='remote';state.profile='current';const result=await backend.loadData();if(result.error){showAuth(`No se pudo cargar la información: ${result.error.message}`);return;}state.members=result.data.members;state.accounts=result.data.accounts;state.currentName=state.members.find((member)=>member.user_id===session.user.id)?.display_name||session.user.email?.split('@')[0]||'Mi cuenta';
  state.movements=result.data.transactions.map((row)=>({id:row.id,description:row.description,category:row.category,date:row.occurred_on,account:accountLabel(row.account_id),accountId:row.account_id,amount:Number(row.amount),type:row.type,icon:row.type==='income'?'↗':'⌂',iconClass:row.type==='income'?'work':row.category.toLowerCase()==='comida'?'food':'home'}));state.payments=result.data.payments.map((row)=>({id:row.id,day:row.due_day,month:'SEP',name:row.name,amount:Number(row.amount),status:row.status,accountId:row.account_id,detail:accountLabel(row.account_id)}));
  renderAccountOptions();hideAuth();addSignOutButton();renderProfile();renderPayments();renderMovements();switchView('overview');toast(state.accounts.length?'Información sincronizada con Supabase':'Sesión iniciada. Falta asociar las cuentas familiares.');
}
async function initializeAuth(){if(!backend?.configured){enterDemo();return;}const {data}=await backend.getSession();if(data?.session)await loadRemoteData(data.session);else showAuth();backend.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session)setTimeout(()=>loadRemoteData(session),0);if(event==='SIGNED_OUT')showAuth('Sesión cerrada.');});}
document.querySelectorAll('.nav-item[data-view], [data-view-link]').forEach((el)=>el.addEventListener('click',()=>switchView(el.dataset.view||el.dataset.viewLink)));[$('addMovementButton'),$('addMovementButton2')].forEach((b)=>b?.addEventListener('click',()=>openModal('movementModal')));[$('addPaymentButton'),$('addPaymentButton2')].forEach((b)=>b?.addEventListener('click',()=>toast('La creación de pagos recurrentes estará disponible en la siguiente conexión.')));
$('profileButton').addEventListener('click',()=> $('profileMenu').classList.toggle('hidden'));$('topProfileButton').addEventListener('click',()=> $('profileMenu').classList.toggle('hidden'));document.querySelectorAll('[data-profile]').forEach((b)=>b.addEventListener('click',()=>{if(state.mode==='remote'&&b.dataset.profile!=='family'){state.profile='current';toast('Tu cuenta personal está protegida; usa Vista familiar para ver el consolidado.');}else state.profile=b.dataset.profile;$('profileMenu').classList.add('hidden');renderProfile();renderMovements();renderPayments();}));
document.querySelectorAll('[data-close-modal]').forEach((b)=>b.addEventListener('click',()=>closeModal(b.dataset.closeModal)));$('movementModal').addEventListener('click',(e)=>{if(e.target.id==='movementModal')closeModal('movementModal')});document.querySelectorAll('input[name="type"]').forEach((input)=>input.addEventListener('change',()=>document.querySelectorAll('.type-option').forEach((x)=>x.classList.toggle('selected',x.querySelector('input').checked))));
$('movementForm').addEventListener('submit',async(e)=>{e.preventDefault();const f=new FormData(e.target);const type=f.get('type');const amount=Number(f.get('amount'));if(state.mode==='remote'){const accountId=f.get('account');if(!accountId){toast('Primero asocia una cuenta familiar en Supabase.');return;}const result=await backend.addTransaction({account_id:accountId,description:f.get('description'),category:f.get('category'),amount,type,occurred_on:f.get('date'),created_by:state.session.user.id});if(result.error){toast(`No se pudo guardar: ${result.error.message}`);return;}await loadRemoteData(state.session);closeModal('movementModal');e.target.reset();toast('Movimiento guardado en Supabase.');return;}state.movements.unshift({id:Date.now(),description:f.get('description'),category:f.get('category'),date:f.get('date'),account:f.get('account'),amount,type,icon:type==='income'?'↗':'⌂',iconClass:type==='income'?'work':f.get('category').toLowerCase()==='comida'?'food':'home'});localStorage.setItem('casa-clara-movements',JSON.stringify(state.movements));renderMovements();closeModal('movementModal');e.target.reset();toast('Movimiento guardado en la demo local');});
['movementSearch','movementTypeFilter','movementCategoryFilter'].forEach((id)=>$(id)?.addEventListener('input',renderMovements));$('helpButton').addEventListener('click',()=>toast('Casa Clara te ayuda a ver tu dinero con más calma.'));$('settingsButton').addEventListener('click',()=>toast(state.mode==='remote'?'Configuración: datos sincronizados con Supabase':'Configuración: demo local activa'));
$('authForm').addEventListener('submit',async(e)=>{e.preventDefault();const message=$('authMessage');message.textContent='Conectando…';const result=await backend.signIn($('authEmail').value.trim(),$('authPassword').value);if(result.error){message.textContent='No pudimos iniciar sesión. Revisa tu correo y contraseña.';return;}message.textContent='';await loadRemoteData(result.data.session);});$('demoButton').addEventListener('click',()=>{enterDemo();toast('Estás viendo datos de ejemplo.');});
renderProfile();renderPayments();renderMovements();switchView('overview');initializeAuth();
