const initialMovements = [
  {id:1,description:'Nómina quincenal',category:'Trabajo',date:'2026-09-01',account:'Cuenta de Eli',amount:5850,type:'income',icon:'↗',iconClass:'work'},
  {id:2,description:'Supermercado Fresh Market',category:'Comida',date:'2026-09-03',account:'Cuenta compartida',amount:186.42,type:'expense',icon:'⌂',iconClass:'food'},
  {id:3,description:'Pago de electricidad',category:'Vivienda',date:'2026-09-03',account:'Cuenta de Wil',amount:128.75,type:'expense',icon:'⌂',iconClass:'home'},
  {id:4,description:'Gasolina',category:'Transporte',date:'2026-09-02',account:'Cuenta de Eli',amount:64.30,type:'expense',icon:'↗',iconClass:'transport'},
  {id:5,description:'Transferencia recibida',category:'Trabajo',date:'2026-09-02',account:'Cuenta de Wil',amount:4100,type:'income',icon:'↗',iconClass:'work'},
  {id:6,description:'Cena familiar',category:'Comida',date:'2026-08-30',account:'Cuenta compartida',amount:92.18,type:'expense',icon:'⌂',iconClass:'food'},
  {id:7,description:'Consulta médica',category:'Salud',date:'2026-08-28',account:'Cuenta de Eli',amount:65,type:'expense',icon:'+',iconClass:'home'}
];
const payments = [
  {id:1,day:'06',month:'SEP',name:'Renta / hipoteca',detail:'Cuenta compartida · vence en 2 días',amount:1200,status:'pending'},
  {id:2,day:'12',month:'SEP',name:'Internet y teléfono',detail:'Cuenta de Wil · vence en 8 días',amount:85,status:'pending'},
  {id:3,day:'18',month:'SEP',name:'Seguro del auto',detail:'Cuenta de Eli · vence en 14 días',amount:150,status:'pending'},
  {id:4,day:'01',month:'SEP',name:'Suscripción de música',detail:'Cuenta de Eli · pagado',amount:14.99,status:'paid'},
  {id:5,day:'03',month:'SEP',name:'Guardería',detail:'Cuenta compartida · pagado',amount:420,status:'paid'}
];
let state = {profile:'eli', view:'overview', movements: JSON.parse(localStorage.getItem('casa-clara-movements') || 'null') || initialMovements};
const $ = (id) => document.getElementById(id);
const money = (n) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const dateLabel = (date) => new Intl.DateTimeFormat('es-US',{day:'2-digit',month:'short'}).format(new Date(`${date}T12:00:00`)).replace('.','');
function visibleMovements(){ if(state.profile==='eli') return state.movements.filter(m=>m.account.includes('Eli') || m.account.includes('compartida')); if(state.profile==='wil') return state.movements.filter(m=>m.account.includes('Wil') || m.account.includes('compartida')); return state.movements; }
function renderProfile(){ const family=state.profile==='family', name=family?'Familia':state.profile==='eli'?'Eli':'Wil', initial=family?'+':name[0]; ['profileName','topProfileLabel'].forEach(id=>$(id).textContent=name); $('profileEmail').textContent=family?'Eli + Wil':'Cuenta personal'; ['profileAvatar','topAvatar'].forEach(id=>{ $(id).textContent=initial; $(id).className=`avatar ${state.profile==='eli'?'avatar-eli':state.profile==='wil'?'avatar-wil':'avatar-family'}`; }); $('pageTitle').innerHTML=family?'Resumen de Eli y Wil <span class="wave">✺</span>':`Buenos días, ${name} <span class="wave">✺</span>`; }
function renderPayments(){ const html=payments.slice(0,3).map(p=>`<div class="payment-item"><div class="payment-date"><strong>${p.day}</strong>${p.month}</div><div class="payment-info"><strong>${p.name}</strong><small>${p.detail}</small></div><span class="payment-amount">${money(p.amount)}</span></div>`).join(''); $('paymentPreview').innerHTML=html; $('fullPaymentList').innerHTML=payments.map(p=>`<div class="full-payment-card"><div class="payment-date"><strong>${p.day}</strong>${p.month}</div><div class="payment-info"><strong>${p.name}</strong><small>${p.detail}</small></div><span class="status ${p.status}">${p.status==='paid'?'Pagado':'Pendiente'}</span><strong class="payment-amount">${money(p.amount)}</strong></div>`).join(''); const pending=payments.filter(p=>p.status==='pending'); $('dueTotal').textContent=money(pending.reduce((a,p)=>a+p.amount,0)); $('pendingCount').textContent=pending.length; $('navPaymentBadge').textContent=pending.length; }
function renderMovements(){ const list=visibleMovements().sort((a,b)=>b.date.localeCompare(a.date)); $('movementPreview').innerHTML=list.slice(0,4).map(m=>`<div class="movement-item"><span class="movement-icon ${m.iconClass}">${m.icon}</span><div class="movement-info"><strong>${m.description}</strong><small>${m.category} · ${m.account}</small></div><span class="movement-amount ${m.type}">${m.type==='income'?'+':'−'}${money(m.amount)}</span></div>`).join(''); const query=($('movementSearch')?.value||'').toLowerCase(); const type=$('movementTypeFilter')?.value||'all'; const category=$('movementCategoryFilter')?.value||'all'; const filtered=list.filter(m=>(!query||`${m.description} ${m.category}`.toLowerCase().includes(query))&&(type==='all'||m.type===type)&&(category==='all'||m.category===category)); $('movementTable').innerHTML=filtered.map(m=>`<div class="table-row"><div class="movement-cell"><span class="movement-icon ${m.iconClass}">${m.icon}</span><strong>${m.description}</strong></div><div><span class="category-chip">${m.category}</span></div><div>${dateLabel(m.date)}</div><div>${m.account}</div><div class="align-right movement-amount ${m.type}">${m.type==='income'?'+':'−'}${money(m.amount)}</div></div>`).join('') || '<div class="empty-state">No hay movimientos con estos filtros.</div>'; const current=list.filter(m=>m.date.startsWith('2026-09')); const income=current.filter(m=>m.type==='income').reduce((a,m)=>a+m.amount,0); const expense=current.filter(m=>m.type==='expense').reduce((a,m)=>a+m.amount,0); $('incomeValue').textContent=money(income); $('expenseValue').textContent=money(expense); $('balanceValue').textContent=money(6500+income-expense); const cats={}; current.filter(m=>m.type==='expense').forEach(m=>cats[m.category]=(cats[m.category]||0)+m.amount); const colors=['#74b98c','#e4bc97','#b9a5d6','#8bbbc5','#e9dcae']; $('categoryList').innerHTML=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,val],i)=>`<div class="category-item"><i style="background:${colors[i]}"></i><span>${name}<small>${Math.round(val/Math.max(expense,1)*100)}% del total</small></span><strong>${money(val)}</strong></div>`).join(''); }
function switchView(view){ state.view=view; document.querySelectorAll('.view-panel').forEach(p=>p.classList.add('hidden')); $(`${view}View`).classList.remove('hidden'); document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); window.scrollTo({top:0,behavior:'smooth'}); }
function openModal(id){ $(id).classList.remove('hidden'); if(id==='movementModal') $('movementForm').date.value=new Date().toISOString().slice(0,10); }
function closeModal(id){ $(id).classList.add('hidden'); }
function toast(message){ $('toast').textContent=message; $('toast').classList.remove('hidden'); setTimeout(()=>$('toast').classList.add('hidden'),2600); }
document.querySelectorAll('.nav-item[data-view], [data-view-link]').forEach(el=>el.addEventListener('click',()=>switchView(el.dataset.view||el.dataset.viewLink)));
[$('addMovementButton'),$('addMovementButton2')].forEach(b=>b?.addEventListener('click',()=>openModal('movementModal'))); [$('addPaymentButton'),$('addPaymentButton2')].forEach(b=>b?.addEventListener('click',()=>toast('La creación de pagos recurrentes estará disponible en la siguiente conexión.')));
$('profileButton').addEventListener('click',()=> $('profileMenu').classList.toggle('hidden')); $('topProfileButton').addEventListener('click',()=> $('profileMenu').classList.toggle('hidden'));
document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>{state.profile=b.dataset.profile; $('profileMenu').classList.add('hidden'); renderProfile(); renderMovements(); toast(state.profile==='family'?'Vista familiar activada':`Ahora estás viendo la cuenta de ${state.profile==='eli'?'Eli':'Wil'}`);}));
document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.closeModal))); $('movementModal').addEventListener('click',e=>{if(e.target.id==='movementModal')closeModal('movementModal')});
document.querySelectorAll('input[name="type"]').forEach(input=>input.addEventListener('change',()=>document.querySelectorAll('.type-option').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked))));
$('movementForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const type=f.get('type');state.movements.unshift({id:Date.now(),description:f.get('description'),category:f.get('category'),date:f.get('date'),account:f.get('account'),amount:Number(f.get('amount')),type,icon:type==='income'?'↗':'⌂',iconClass:type==='income'?'work':f.get('category').toLowerCase()==='comida'?'food':'home'});localStorage.setItem('casa-clara-movements',JSON.stringify(state.movements));renderMovements();closeModal('movementModal');e.target.reset();toast('Movimiento guardado correctamente');});
['movementSearch','movementTypeFilter','movementCategoryFilter'].forEach(id=>$(id)?.addEventListener('input',renderMovements));
$('helpButton').addEventListener('click',()=>toast('Casa Clara te ayuda a ver tu dinero con más calma.')); $('settingsButton').addEventListener('click',()=>toast('Configuración: moneda USD · modo local activo'));
renderProfile();renderPayments();renderMovements();switchView('overview');
